apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teamtask

resources:
  - ../../base
  - teamtask-backend-sealedsecret.yaml
  - teamtask-postgres-sealedsecret.yaml

images:
  - name: teamtask-backend
    newName: ghcr.io/minhpham485/teamtask-manager-backend
    newTag: 3393f790219ddf53fc8d32ca8228960eacc43b8a
  - name: teamtask-frontend
    newName: ghcr.io/minhpham485/teamtask-manager-frontend
    newTag: 3393f790219ddf53fc8d32ca8228960eacc43b8a

patches:
  - path: ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: teamtask
