apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teamtask
spec:
  ingressClassName: nginx
  rules:
    - host: minhph.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  name: http
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http
